[package]
name = "motors"
version = "0.1.0"
authors=["ToTheAnd"]
edition = "2021"
license = "GPL-3"
description="A collection of several games and engines"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.1"
#text_io = "0.1.12"
rand = "0.8.5"
# The latest published version has a bug in the pdep implementation where it panics when called with u64::MAX,
# but this is fixed in the git repo.
bitintr = { git = "https://github.com/gnzlbg/bitintr" }
colored = "2.0.4"
strum = "0.25.0"
strum_macros = "0.25.3"
derive_more = { version = "1.0.0-beta.6", features=["full"] }
itertools = "0.12.0"
lazy_static = "1.4.0"
clap = { version = "4.4.8", features = ["derive"] }
chrono = "0.4.31"
