[package]
name = "motors"
version = "0.1.0"
authors = ["ToTheAnd"]
edition = "2021"
license = "GPL-3"
description = "A collection of several games and engines"


[dependencies]
gears = { path = "../gears", default-features = false }
#num = "0.4.1"
##text_io = "0.1.12"
rand = "0.8.5"
## The latest published version has a bug in the pdep implementation where it panics when called with u64::MAX,
## but this is fixed in the git repo.
#bitintr = { git = "https://github.com/gnzlbg/bitintr" }
colored = "2.0.4"
strum = "0.26.1"
strum_macros = "0.26.1"
derive_more = { version = "1.0.0-beta.6", features = ["full"] }
itertools = "0.12.0"
dyn-clone = "1.0.17"
#chrono = "0.4.31" # Not really necessary
static_assertions = "1.1.0"
crossbeam-channel = "0.5.8"
crossbeam-utils = "0.8.19"
portable-atomic = "1.6.0"
arrayvec = "0.7.4"

[features]
default = ["chess", "mnk", "random_mover", "generic_negamax", "caps"]
random_mover = []
naive_negamax = [] # not a default feature because it's borderline useless
generic_negamax = []
caps = ["chess"]

generic-engines = ["random_mover", "generic_negamax"]
chess-engines = ["caps"]
mnk-engines = [] # does nothing at the moment

chess = ["gears/chess"]
mnk = ["gears/mnk"]

[lib]
name = "motors"
path = "src/lib.rs"

[[bin]]
name = "motors"
path = "src/main.rs"