[package]
name = "gears"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "perft_bench"
harness = false

[dev-dependencies]
criterion = "0.5.1"


[dependencies]
num = "0.4.1"
rand = "0.8.5"
# bitintr is bugged and unmaintained
colored = "2.1.0"
strum = "0.26.3"
strum_macros = "0.26.4"
derive_more = { version = "1.0.0", features = ["full"] }
itertools = "0.13.0"
chrono = "0.4.38"
static_assertions = "1.1.0"
dyn-clone = "1.0.17"
arrayvec = "0.7.6"
edit-distance = "2.1.2"
arbitrary = { version = "1.3.2", features = ["derive"] }

[features]
default = ["chess", "mnk", "ataxx", "uttt", "unsafe"]
unsafe = []
chess = []
mnk = []
ataxx = []
uttt = []
