[package]
name = "pliers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gears = { path = "../gears", default-features = false }
derive_more = "1.0.0-beta.6"